language: python
python:
  - '3.6'
  - '3.7'
install:
  - pip install -e .
  - pip install pytest pytest-cov
  - pip install coveralls
script:
  - pytest --cov tinycards
after_success:
  - coveralls
before_deploy:
  - rm -rf build/
  - rm -rf dist/
  - rm -rf *.egg-info/
deploy:
  provider: pypi
  user: floscha
  password:
    secure: fGNlMnLPdmIUulX2oNQF4a78Utfce2Dg9Sld/EAyBkM5B0kz80SxrXHkOOdIfDyOwSnAJAf2nSJcGmbAH2ZfYdG6Bmyhl5ZgH8OzTqUbZdzym2gPKQ2z+aaqxZ0tXrEBMNm6oMhFAG47aPKWTiWynVa4KpYQnl6nfWxPZvdgK60a8WNXKnjgQd8/h6bW1SDb6wY/dy+TTQ5RGxqsqkwG9TuhmGCzopBLdnLhwHL3fr0XivWTqxxBOWvt5GS404X7MrGfjYvDQUYcaUfqDSvNXS5TNYMPBIfB2RumgLXqc7Z88vZ1j26yG364N/9WOOLINOxXkLVCl3+RRyzXGk30vQCN6VSVQe9vXH8XsrTZBepArOm2tYf2Su785pKQjQiC5KwsbWBbj9dS187yewXe5dL9mvwOTOxlzyiXJRgbt40htfYcnx6JrNc1sLxN9QYcGHhazkGh1FzAAcZL7RBazO86zMTP5zZuF16gI7kkMQdI0cj5y8LuN0T1TQ8pehH8kKkqVneJSGtKsLbRB6Sw6dl1iAyH2qKMcvpPk/kM+LzC8NGm1m4gGOBcLKgdb42xQSb5sq7hQrO4Zu0wt1xm3gpmpXD6Ncdx17ngQd1KqSCChoEe/ZWMks/j6wf7tQP/+vShQvyF461UzTYdbJdRijz0WKYDECIaAKsm2cN8SOc=
  on:
    tags: true
env:
  global:
  - TINYCARDS_IDENTIFIER=njam-test
  - TINYCARDS_PASSWORD=gRaVeATiod
  - secure: YtA+3hTUUXrWqUpknuPwUeA+E2mQVBxtpSpPphtwVJuvaFKTkkdj4rt2vKNKUrapguwNjAGiwJXKOyNxS+QG1KfE0O5uECHfEGDnM5kvOvoNX/Cql25HgzJaUA4MnOgVoxVb+5+CYqPHI21uE8I/jb7NrQ/Bu2xWh/i3OFP354Ni9aU//mGu7AKcaXxcFRLKbir4NFpjcJXvYzxselRtWLlrT1KpanBja/PubUvwuxpMuguVnY0QeOuDfRmasVUzya/uu7sBtHidbndm0Ca1PVaK/BtoFWP9hTHaJi5KWx4ihBIV6oXnZh3G9WSMo7PPMCiO1U0ppv/LFwENc+65QKd1ye1lQ8kgHh7esEPoRSE7ZgUQfxsYTaxNH7AUUTUhiRfdThc6KMxTC3bPDJL0lEpSADxq/t/ayQoDMgYTRZKpPx4vi1b4m75YlEsHuMfe9re9NXS/v34FUfdUrBL19i/SY6njAtUSbBmv/2sHanBw4C3CR9+yTTNKaDvJqAhUtJ4WWt4NizL51Ci4CXbOpSMMUQxzpOtE7vAF2jfUPrl2GtPD8z2PEcveb7ejFkmmINGFEADniILwrKmRiPKJcJDW+aH0+TdDSc7wOVx3RT4Y4LiWhTkakik6QB/cPZ+odoD5sWrW5CzWT227MBRnZ1doCrR0uzbbOKOZr/MrEno=
  - secure: iT7iBCmirS7y+Y+9EFsCtL396i/DYnoqiGEGB2+ZBYnPcMoSLjApvoJGBmyCcYE/v0T7g9+t/TJCuceFJtVrOQLshGw+SZ9KiPMHyfEqGBN187Zpx2n+TEtA+YcgsVIw8NDMLCtOUUfuwR7fSoR5N0gEL673TUDsCw0h9qxCpG872ZKge1bsAOHgGMnm+eE5rk2GDVjLo1CJOBLxhoRHojq9zNu00Ns/d061KowkcM4+CDfhBH7nfYEQnqQvD0t5qXqNZsvt1Uy4iexzSqmKnm+TRe+3vCHp3NmZkRaZsrkGNqUp97l/E6FN1pD90/1n+JIkcBZ7x7X17f3Ip83NKMmlyUHzoVbawCABDKHchp9Ze8BvxWQQl7OH3V0aZMTzMmi7z2zgFPVELGNPHnlvJSnuucsBp3UOGZG2IMPfMNLR/7biL34PdYFxTxRo83N58z94+2Y/4bcWBuZfejiJVFH9ZI2o+/jj1tOWFoBchiA5Ko784oDONGcRRiQnQv2o9X71IElXehlLrkOoW6jwyzfG3Ur56rB/daBySV5JDuzM7DTDgSsZTSCITdtcz0E5K9gyKVYEgJYKH3nuYDeZ6Po98u1QP53xYIEf5stKrykLekIYJ5oaG+4i9qcZVQsSX4Cf8EtAFpWeRyrRzlxKY2kZTIYioquB0t9oUXd0LQg=
